github_username: bot_username
github_password: bot_password
github_pull_request_title: SPDX Document Automatic Update
git_name: Bot's Name for Commits
git_email: bots_email@email.com
git_commit_message: SPDX Document Automatic Update
gmail_email: bot_email@gmail.com
gmail_password: bot_email_password
notification_email: email_to_notify@email.com
notification_subject: New SPDX Document Ready
notification_message: Your new SPDX document is ready.
